name: Deploy to heroku
on:
  release:
    types: [published]
jobs:
  deploy_to_heroku_upon_publish_of_release:
    runs-on: ubuntu-latest
    steps:
    - name: get latest release with tag
      id: latestrelease
      run: |
        echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/siawli/VTTP-Project/releases/latest | jq '.tag_name' | sed 's/\"//g')"
    - name: confirm release tag
      run: |
        echo ${{ steps.latestrelease.outputs.releasetag }}
    - name: tag checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.latestrelease.outputs.releasetag }}
    - name: deploy
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "vttp-project-healthy" #Must be unique in Heroku
        heroku_email: ${{secrets.email}}