name: Test
on: [ "push" ]
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - name: Run test
      run: mvn clean verify
    - name: Generate coverge badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
    - name: Upload coverage badge to DigitalOcean spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.pafsiawliaccess }}
        secret_key: ${{ secrets.pafsiawlisecret }}
        space_name: paf-siawli
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
    - name: Upload coverage report
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.pafsiawliaccess }}
        secret_key: ${{ secrets.pafsiawlisecret }}
        space_name: paf-siawli
        space_region: sgp1
        source: target/site/jacoco
        out_dir: coverage/${{ github.event.repository.name }}/report 